//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_9_Error_Handle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Courses
    {
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Notes { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual student student { get; set; }
    }
}
