//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int ID_Maj { get; set; }
        public string Descrption { get; set; }
        public string Name { get; set; }
        public Nullable<int> MajorId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
